import { TOSC } from './tosc';

export const examples = [
  {
    id: 0,
    name: 'Example 0 really long name with short pro',
    pronoun: 'xey',
    tosc: new TOSC('RG+B+B+'),
  },
  {
    id: 1,
    name: 'Example 1 long name',
    pronoun: 'sie',
    tosc: new TOSC('RGBB'),
  },
  { id: 2, name: 'Example 2', pronoun: 'he', tosc: new TOSC('RR+GG') },
  {
    id: 3,
    name: 'Example 3 really long name with long pro',
    pronoun: 'they/them/themselves',
    tosc: new TOSC('G+G+GG+'),
  },
  { id: 4, name: 'Example 4', pronoun: '', tosc: new TOSC('RBGR+') },
  {
    id: 5,
    name: 'Example 5 long name',
    pronoun: 'they/them/themselves',
    tosc: new TOSC('G+RGG+'),
  },
  { id: 6, name: 'Example 6', pronoun: '', tosc: new TOSC('R+G+G+G+') },
  { id: 7, name: 'Example 7', pronoun: 'xey', tosc: new TOSC('B+R+G+G') },
  { id: 8, name: 'Example 8', pronoun: 'ze/hir', tosc: new TOSC('B+RGG') },
  { id: 9, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 10, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 11, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 12, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 13, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 14, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 15, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 16, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 17, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 18, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 19, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 20, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 21, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 22, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 23, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 24, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 25, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
  { id: 26, name: 'Example 9', pronoun: 'she', tosc: new TOSC('RBB+B') },
];
